### ISSUE TITLE
Probing existing Clang warnings

### ISSUE THREAD

**Issue by Julien-Elie** [rra/rra-c-util#9]
_m4/cc-flags.m4_ checks for supported warning flags but it seems that Clang always reports them as available because unknown options are not an error by default, but only a warning.
It defeats the purpose of m4/cc-flags.m4...

```
configure:31771: checking if clang supports -Wformat-overflow=2
configure:31796: clang -c -g -O2 -Wformat-overflow=2  conftest.c >&5
warning: unknown warning option '-Wformat-overflow=2'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
1 warning generated.
configure:31796: $? = 0
configure:31805: result: yes
```

Besides, even for real Clang flags, the check should only report them as available when using a release supporting it (some warning options are not present in all versions).

I don't know whether you wish to do something in rra-c-util about that.  You could for instance check for `$CLANG` in `RRA_PROG_CC_FLAG` and then add `-Werror=unknown-warning-option` for the check, or add a new parameter to `RRA_PROG_CC_FLAG` for additional flags to use during the probe.

For INN, I've added that quick work-around (which works).
If the compiler recognizes `-Werror=unknown-warning-option`, add it to `$CFLAGS`:

```
RRA_PROG_CC_FLAG([-Werror=unknown-warning-option],
                 [CFLAGS="$CFLAGS -Werror=unknown-warning-option"], [])
```

Then run all the `RRA_PROG_CC_FLAG` probes for compiler warnings, hardening flags etc.
And afterwards, remove that flag from `$CFLAGS`:

```
CFLAGS=`AS_ECHO(["${CFLAGS}"]) | sed 's/ -Werror=unknown-warning-option//'`
```

**Comment by rra** [comment]
Thanks, good catch! I have updated those macros to add `-Werror=unknown-warning-option` when the compiler or linker is Clang.
